package com.queens.puzzle.ui.designsystem.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val PrimaryLight = Color(0xFF2E7D32)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFC8EAC0)
val OnPrimaryContainerLight = Color(0xFF0D3B12)
val SecondaryLight = Color(0xFF6B5B4D)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE8DDD2)
val OnSecondaryContainerLight = Color(0xFF3D3226)
val TertiaryLight = Color(0xFFC9A227) // celebration / win accent
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFF5E7B8)
val OnTertiaryContainerLight = Color(0xFF4A3B0A)
val ErrorLight = Color(0xFFE08E45) // conflict — warm amber, reads as "warning" not alarm
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFBDDBE)
val OnErrorContainerLight = Color(0xFF6B3A0A)
val BackgroundLight = Color(0xFFFAF9F6)
val OnBackgroundLight = Color(0xFF1C1B1A)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF1C1B1A)
val SurfaceVariantLight = Color(0xFFE7E2DA)
val OnSurfaceVariantLight = Color(0xFF49463F)
val OutlineLight = Color(0xFF8B8579)
val OutlineVariantLight = Color(0xFFD8D2C6)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFFAF9F6)
val SurfaceContainerLight = Color(0xFFEFEAE1)
val SurfaceContainerHighLight = Color(0xFFFFFFFF)
val SurfaceContainerHighestLight = Color(0xFFD8D2C6)
val SurfaceBrightLight = Color(0xFFFFFFFF)
val SurfaceDimLight = Color(0xFFE2DCD0)
val InverseSurfaceLight = Color(0xFF32302B)
val InverseOnSurfaceLight = Color(0xFFF5F2EC)
val InversePrimaryLight = Color(0xFF8AD47A)
val ScrimLight = Color(0xFF171614)

// Dark scheme
val PrimaryDark = Color(0xFF7BC96C)
val OnPrimaryDark = Color(0xFF0F3512)
val PrimaryContainerDark = Color(0xFF23481F)
val OnPrimaryContainerDark = Color(0xFFBEE8B0)
val SecondaryDark = Color(0xFFC7B6A5)
val OnSecondaryDark = Color(0xFF3D3226)
val SecondaryContainerDark = Color(0xFF4A3E32)
val OnSecondaryContainerDark = Color(0xFFE8DDD2)
val TertiaryDark = Color(0xFFE3C158)
val OnTertiaryDark = Color(0xFF4A3B0A)
val TertiaryContainerDark = Color(0xFF5C4A12)
val OnTertiaryContainerDark = Color(0xFFF5E7B8)
val ErrorDark = Color(0xFFF0A868)
val OnErrorDark = Color(0xFF4A2A08)
val ErrorContainerDark = Color(0xFF6B3A0A)
val OnErrorContainerDark = Color(0xFFFBDDBE)
val BackgroundDark = Color(0xFF171614)
val OnBackgroundDark = Color(0xFFE8E6E1)
val SurfaceDark = Color(0xFF1F1E1B)
val OnSurfaceDark = Color(0xFFE8E6E1)
val SurfaceVariantDark = Color(0xFF3A3733)
val OnSurfaceVariantDark = Color(0xFFC9C4B8)
val OutlineDark = Color(0xFF6E6A62)
val OutlineVariantDark = Color(0xFF4A463E)
val SurfaceContainerLowestDark = Color(0xFF121110)
val SurfaceContainerLowDark = Color(0xFF1F1E1B)
val SurfaceContainerDark = Color(0xFF26241F)
val SurfaceContainerHighDark = Color(0xFF2E2B26)
val SurfaceContainerHighestDark = Color(0xFF4A463E)
val SurfaceBrightDark = Color(0xFF3A3733)
val SurfaceDimDark = Color(0xFF171614)
val InverseSurfaceDark = Color(0xFFE8E6E1)
val InverseOnSurfaceDark = Color(0xFF1F1E1B)
val InversePrimaryDark = Color(0xFF2E7D32)
val ScrimDark = Color(0xFF171614)

// Extended roles
val SuccessGreen = Color(0xFF4C8C6B)
val SuccessGreenDark = Color(0xFF7FB899)
val BoardSquareLight = Color(0xFFEEEED2)
val BoardSquareDark = Color(0xFF769656)
val QueenOnLightSquare = Color(0xFF3D3226)
val QueenOnDarkSquare = Color(0xFF18130F)
val QueenConflictLight = Color(0xFF8A4E12)
val QueenConflictDark = Color(0xFFF0A868)
val ConflictTintLight = Color(0x66E08E45)
val ConflictTintDark = Color(0x59F0A868)
val AttackMarkOnLightSquare = Color(0x8C3D3226)
val AttackMarkOnDarkSquare = Color(0x99F5EFE4)
val WinHeadlineLight = Color(0xFF8A6A0E)
val WinGradientTopLight = Color(0xFFFBF3DE)
val WinGradientTopDark = Color(0xFF2A2410)
